# Linear Algebra and Scientific Computing Libraries
## Mehmet Gönen
## October 17, 2022

NumPy is the core scientific library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

In [1]:
# load libraries
import numpy as np
import scipy.sparse as sp

## Creating a vector

In [2]:
# create a vector
vector = np.array([1, 2, 3])
print(vector)
print(vector.shape)
print(vector.size)
print(vector.ndim)

[1 2 3]
(3,)
3
1


In [3]:
# create a row vector
row_vector = np.array([[1, 2, 3]])
print(row_vector)
print(row_vector.shape)
print(row_vector.size)
print(row_vector.ndim)

[[1 2 3]]
(1, 3)
3
2


In [4]:
# create a column vector
column_vector = np.array([[1], [2], [3]])
print(column_vector)
print(column_vector.shape)
print(column_vector.size)
print(column_vector.ndim)

[[1]
 [2]
 [3]]
(3, 1)
3
2


## Creating a matrix

In [5]:
# create a matrix
matrix = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
print(matrix)
print(matrix.shape)
print(matrix.size)
print(matrix.ndim)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
6
2


## Creating a sparse matrix

In [6]:
# create a matrix
matrix = np.array([[0, 0],
                   [0, 4],
                   [5, 0]])
print(matrix)
print(matrix.shape)
print(matrix.size)
print(matrix.ndim)

[[0 0]
 [0 4]
 [5 0]]
(3, 2)
6
2


In [7]:
# create a sparse matrix
sparse_matrix = sp.csr_matrix(matrix)
print(sparse_matrix)
print(sparse_matrix.shape)
print(sparse_matrix.size)
print(sparse_matrix.ndim)

  (1, 1)	4
  (2, 0)	5
(3, 2)
2
2


In [8]:
# create an empty sparse matrix
empty_sparse_matrix = sp.csr_matrix((4, 5))
print(empty_sparse_matrix)
print(empty_sparse_matrix.shape)
print(empty_sparse_matrix.size)
print(empty_sparse_matrix.ndim)


(4, 5)
0
2


## Selecting elements

In [9]:
# create a vector
vector = np.array([1, 2, 3, 4, 5, 6])

# create a matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [10]:
# select the third element of vector
print(vector[2])

3


In [11]:
# select the second row and the third column of matrix
print(matrix[1, 2])

6


In [12]:
# select all elements of vector
print(vector[:])

[1 2 3 4 5 6]


In [13]:
# select everything up to and including the third element
print(vector[:3])

[1 2 3]


In [14]:
# select everything after the third element
print(vector[3:])

[4 5 6]


In [15]:
# select the last element
print(vector[-1])

6


In [16]:
# select the first two rows and all columns of matrix
print(matrix[:2,:])

[[1 2 3]
 [4 5 6]]


In [17]:
# select all rows and the second column of matrix
print(matrix[:,1:2])

[[2]
 [5]
 [8]]


## Finding maximum and minimum values

In [18]:
# create a matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [19]:
# return maximum element
print(np.max(matrix))

9


In [20]:
# return minimum element
print(np.min(matrix))

1


In [21]:
# find maximum element in each column
print(np.max(matrix, axis = 0))

[7 8 9]


In [22]:
# find minimum element in each row
print(np.min(matrix, axis = 1))

[1 4 7]


## Calculating average, variance, and standard deviation

In [23]:
# create a matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [24]:
# return mean
print(np.mean(matrix))

5.0


In [25]:
# return variance
print(np.var(matrix))

6.666666666666667


In [26]:
# return standard deviation
print(np.std(matrix))

2.581988897471611


In [27]:
# find the mean value in each column
print(np.mean(matrix, axis = 0))

[4. 5. 6.]


## Reshaping arrays

In [28]:
# create 4x3 matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

In [29]:
# reshape matrix into 2x6 matrix
reshaped_matrix = matrix.reshape((2, 6))
print(reshaped_matrix)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [30]:
reshaped_matrix = matrix.reshape((1, -1))
print(reshaped_matrix)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]


In [31]:
reshaped_matrix = matrix.reshape(12)
print(reshaped_matrix)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


## Transposing a vector or a matrix

In [32]:
# create a matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [33]:
# transpose matrix
transposed_matrix = matrix.transpose()
print(transposed_matrix)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [34]:
# create a vector
vector = np.array([1, 2, 3, 4, 5, 6])

In [35]:
# transpose vector
transposed_vector = vector.transpose()
print(transposed_vector)

[1 2 3 4 5 6]


In [36]:
# create a row vector
row_vector = np.array([[1, 2, 3, 4, 5, 6]])

In [37]:
# transpose row vector
transposed_vector = row_vector.transpose()
print(transposed_vector)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [38]:
# create a column vector
column_vector = np.array([[1], [2], [3], [4], [5], [6]])

In [39]:
# transpose column vector
transposed_vector = column_vector.transpose()
print(transposed_vector)

[[1 2 3 4 5 6]]


## Flattening a matrix

In [40]:
# create a matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [41]:
# flatten a matrix
flattened_matrix = matrix.flatten()
print(flattened_matrix)

[1 2 3 4 5 6 7 8 9]
